(clear)
(build-cube)
(reset-camera)
(define cam (get-camera-transform))
(define forgat (vector 0 0 0))
(every-frame (begin
    (set-camera-transform (mmul cam (mrotate forgat)))
    (when (osc-msg "/forgat")
        (display (osc 0))
        (set! forgat (vmul (vector (osc 2) (osc 0) (osc 1)) 1))
    )))
(osc-source "5678")
(osc-destination "osc.udp://localhost:5670")
(osc-send "/snowballjs/listen" "si" (list "/forgat" 5678))
(osc-send "/valami" "s" (list "hej!"))